routes/web.php
<?php
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('send-mail', [MailController::class, 'index']);

Route::resource('analytics', 'AnalyticsController');

Route::resource('users', 'UserController');

Route::resource('analytics', 'AnalyticsController');


Route::resource('proceedings', 'ProceedingController');

Route::resource('applicants', 'ApplicantController');

Route::resource('summoneds', 'SummonedController');

Route::resource('proceedingStates', 'ProceedingStateController');

Route::resource('actions', 'ActionController');

Route::resource('actionTypes', 'ActionTypesController');

Route::resource('dues', 'DuesController');

Route::resource('purses', 'PurseController');

Route::resource('documents', 'DocumentController');

app/Models/Summoned.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;
/**
 * @SWG\Definition(
 *      definition="Summoned",
 *      required={"name", "identification", "email", "address", "phone", "created_at"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="identification",
 *          description="identification",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="address",
 *          description="address",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Summoned extends Model
{
    use SoftDeletes;

    public $table = 'summoneds';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'identification',
        'lastname',
        'email',
        'address',
        'phone'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'lastname' => 'string',
        'identification' => 'string',
        'email' => 'string',
        'address' => 'string',
        'phone' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'identification' => 'required',

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function proceedings()
    {
        return $this->hasMany(\App\Models\Proceedings::class, 'summoneds_id');
    }


    public function getById($id)
    {
            return DB::table('summoneds')
                ->where([
                    ['summoneds.id', '=', $id]
                ])
                ->whereNull('summoneds.deleted_at')
                ->select('summoneds.*')
                ->get();
    }

    public function get()
    {
            return DB::table('summoneds')
            ->where([
                    ['summoneds.name', '!=', '']
                ])
                ->whereNull('summoneds.deleted_at')
                ->select('summoneds.*')
                ->orderBy('name', 'ASC')
                ->get();
    }
}

app/Http/Controllers/SummonedController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\SummonedDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateSummonedRequest;
use App\Http\Requests\UpdateSummonedRequest;
use App\Repositories\SummonedRepository;
use App\Http\Controllers\AppBaseController;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Response;

class SummonedController extends AppBaseController
{
    /** @var  SummonedRepository */
    private $summonedRepository;

    public function __construct(SummonedRepository $summonedRepo)
    {
        $this->summonedRepository = $summonedRepo;
    }

    /**
     * Display a listing of the Summoned.
     *
     * @param SummonedDataTable $summonedDataTable
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(SummonedDataTable $summonedDataTable)
    {
        return $summonedDataTable->render('summoneds.index');
    }

    /**
     * Show the form for creating a new Summoned.
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function create()
    {
        return view('summoneds.create');
    }

    /**
     * Store a newly created Summoned in storage.
     *
     * @param CreateSummonedRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function store(CreateSummonedRequest $request)
    {
        $input = $request->all();

        $summoned = $this->summonedRepository->create($input);

        Flash::success('Convocado creado correctamente.');

        return redirect(route('summoneds.index'));
    }

    /**
     * Display the specified Summoned.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function show($id)
    {
        $summoned = $this->summonedRepository->find($id);

        if (empty($summoned)) {
            Flash::error('Convocado no encontrado');

            return redirect(route('summoneds.index'));
        }

        return view('summoneds.show')->with('summoned', $summoned);
    }

    /**
     * Show the form for editing the specified Summoned.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function edit($id)
    {
        $summoned = $this->summonedRepository->find($id);

        if (empty($summoned)) {
            Flash::error('Convocado no encontrado');

            return redirect(route('summoneds.index'));
        }

        return view('summoneds.edit')->with('summoned', $summoned);
    }

    /**
     * Update the specified Summoned in storage.
     *
     * @param  int              $id
     * @param UpdateSummonedRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function update($id, UpdateSummonedRequest $request)
    {
        $summoned = $this->summonedRepository->find($id);

        if (empty($summoned)) {
            Flash::error('Convocado no encontrado');

            return redirect(route('summoneds.index'));
        }

        $summoned = $this->summonedRepository->update($request->all(), $id);

        Flash::success('Convocado actualizado correctamente.');

        return redirect(route('summoneds.index'));
    }

    /**
     * Remove the specified Summoned from storage.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function destroy($id)
    {
        $summoned = $this->summonedRepository->find($id);

        if (empty($summoned)) {
            Flash::error('Convocado no encontrado');

            return redirect(route('summoneds.index'));
        }

        $this->summonedRepository->delete($id);

        Flash::success('Summoned deleted successfully.');

        return redirect(route('summoneds.index'));
    }
}

resources/views/summoneds/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Convocado
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'summoneds.store']) !!}

                        @include('summoneds.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/summoneds/datatables_actions.blade.php
{!! Form::open(['route' => ['summoneds.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('summoneds.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('summoneds.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/summoneds/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Summoned
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($summoned, ['route' => ['summoneds.update', $summoned->id], 'method' => 'patch']) !!}

                        @include('summoneds.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/summoneds/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombres:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('lastname', 'Apellidos:') !!}
    {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
</div>

<!-- Identification Field -->
<div class="form-group col-sm-6">
    {!! Form::label('identification', 'Identificación:') !!}
    {!! Form::number('identification', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Dirección:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Telefono:') !!}
    {!! Form::number('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('applicants.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/summoneds/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Convocados</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('summoneds.create') }}">Agregar nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('summoneds.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/summoneds/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Summoned
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('summoneds.show_fields')
                    <a href="{{ route('summoneds.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/summoneds/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $summoned->name }}</p>
</div>

<!-- Identification Field -->
<div class="form-group">
    {!! Form::label('identification', 'Identification:') !!}
    <p>{{ $summoned->identification }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $summoned->email }}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{{ $summoned->address }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $summoned->phone }}</p>
</div>

resources/views/summoneds/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
<div class="table-responsive">
	{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered table-responsive']) !!}
</div>
@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection