routes/web.php
<?php
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('send-mail', [MailController::class, 'index']);

Route::resource('analytics', 'AnalyticsController');

Route::resource('users', 'UserController');

Route::resource('analytics', 'AnalyticsController');


Route::resource('proceedings', 'ProceedingController');

Route::resource('applicants', 'ApplicantController');

Route::resource('summoneds', 'SummonedController');

Route::resource('proceedingStates', 'ProceedingStateController');

Route::resource('actions', 'ActionController');

Route::resource('actionTypes', 'ActionTypesController');

Route::resource('dues', 'DuesController');

Route::resource('purses', 'PurseController');

Route::resource('documents', 'DocumentController');

app/Models/ProceedingState.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;
/**
 * @SWG\Definition(
 *      definition="ProceedingState",
 *      required={"name", "description", "created_at"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class ProceedingState extends Model
{
    use SoftDeletes;

    public $table = 'proceeding_states';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'description' => 'required',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function proceedings()
    {
        return $this->hasMany(\App\Models\Proceedings::class, 'proceeding_states_id');
    }

    public function getById($id)
    {
            return DB::table('proceeding_states')
                ->where([
                    ['proceeding_states.id', '=', $id]
                ])
                ->whereNull('proceeding_states.deleted_at')
                ->select('proceeding_states.*')
                ->get();
    }

    public function get()
    {
            return DB::table('proceeding_states')
                ->whereNull('proceeding_states.deleted_at')
                ->select('proceeding_states.*')
                ->get();
    }
}

app/Http/Controllers/ProceedingStateController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProceedingStateDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateProceedingStateRequest;
use App\Http\Requests\UpdateProceedingStateRequest;
use App\Repositories\ProceedingStateRepository;
use App\Http\Controllers\AppBaseController;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Response;

class ProceedingStateController extends AppBaseController
{
    /** @var  ProceedingStateRepository */
    private $proceedingStateRepository;

    public function __construct(ProceedingStateRepository $proceedingStateRepo)
    {
        $this->proceedingStateRepository = $proceedingStateRepo;
    }

    /**
     * Display a listing of the ProceedingState.
     *
     * @param ProceedingStateDataTable $proceedingStateDataTable
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(ProceedingStateDataTable $proceedingStateDataTable)
    {
        return $proceedingStateDataTable->render('proceeding_states.index');
    }

    /**
     * Show the form for creating a new ProceedingState.
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function create()
    {
        return view('proceeding_states.create');
    }

    /**
     * Store a newly created ProceedingState in storage.
     *
     * @param CreateProceedingStateRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function store(CreateProceedingStateRequest $request)
    {
        $input = $request->all();

        $proceedingState = $this->proceedingStateRepository->create($input);

        Flash::success('Proceeding State saved successfully.');

        return redirect(route('proceedingStates.index'));
    }

    /**
     * Display the specified ProceedingState.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function show($id)
    {
        $proceedingState = $this->proceedingStateRepository->find($id);

        if (empty($proceedingState)) {
            Flash::error('Proceeding State not found');

            return redirect(route('proceedingStates.index'));
        }

        return view('proceeding_states.show')->with('proceedingState', $proceedingState);
    }

    /**
     * Show the form for editing the specified ProceedingState.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function edit($id)
    {
        $proceedingState = $this->proceedingStateRepository->find($id);

        if (empty($proceedingState)) {
            Flash::error('Proceeding State not found');

            return redirect(route('proceedingStates.index'));
        }

        return view('proceeding_states.edit')->with('proceedingState', $proceedingState);
    }

    /**
     * Update the specified ProceedingState in storage.
     *
     * @param  int              $id
     * @param UpdateProceedingStateRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function update($id, UpdateProceedingStateRequest $request)
    {
        $proceedingState = $this->proceedingStateRepository->find($id);

        if (empty($proceedingState)) {
            Flash::error('Proceeding State not found');

            return redirect(route('proceedingStates.index'));
        }

        $proceedingState = $this->proceedingStateRepository->update($request->all(), $id);

        Flash::success('Proceeding State updated successfully.');

        return redirect(route('proceedingStates.index'));
    }

    /**
     * Remove the specified ProceedingState from storage.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function destroy($id)
    {
        $proceedingState = $this->proceedingStateRepository->find($id);

        if (empty($proceedingState)) {
            Flash::error('Proceeding State not found');

            return redirect(route('proceedingStates.index'));
        }

        $this->proceedingStateRepository->delete($id);

        Flash::success('Proceeding State deleted successfully.');

        return redirect(route('proceedingStates.index'));
    }
}

resources/views/proceeding_states/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Estado de Expediente
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'proceedingStates.store']) !!}

                        @include('proceeding_states.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/proceeding_states/datatables_actions.blade.php
{!! Form::open(['route' => ['proceedingStates.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('proceedingStates.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('proceedingStates.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/proceeding_states/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Estado de Expediente
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($proceedingState, ['route' => ['proceedingStates.update', $proceedingState->id], 'method' => 'patch']) !!}

                        @include('proceeding_states.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/proceeding_states/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombre:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Descripción:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('proceedingStates.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/proceeding_states/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Estados de Expedientes</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('proceedingStates.create') }}">Agregar nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('proceeding_states.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/proceeding_states/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Proceeding State
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('proceeding_states.show_fields')
                    <a href="{{ route('proceedingStates.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/proceeding_states/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $proceedingState->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $proceedingState->description }}</p>
</div>

resources/views/proceeding_states/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
<div class="table-responsive">
	{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered table-responsive']) !!}
</div>
@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection