routes/web.php
<?php
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('send-mail', [MailController::class, 'index']);

Route::resource('analytics', 'AnalyticsController');

Route::resource('users', 'UserController');

Route::resource('analytics', 'AnalyticsController');


Route::resource('proceedings', 'ProceedingController');

Route::resource('applicants', 'ApplicantController');

Route::resource('summoneds', 'SummonedController');

Route::resource('proceedingStates', 'ProceedingStateController');

Route::resource('actions', 'ActionController');

Route::resource('actionTypes', 'ActionTypesController');

Route::resource('dues', 'DuesController');

Route::resource('purses', 'PurseController');

Route::resource('documents', 'DocumentController');

app/Http/Controllers/ActionTypesController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ActionTypesDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateActionTypesRequest;
use App\Http\Requests\UpdateActionTypesRequest;
use App\Repositories\ActionTypesRepository;
use App\Http\Controllers\AppBaseController;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Response;

class ActionTypesController extends AppBaseController
{
    /** @var  ActionTypesRepository */
    private $actionTypesRepository;

    public function __construct(ActionTypesRepository $actionTypesRepo)
    {
        $this->actionTypesRepository = $actionTypesRepo;
    }

    /**
     * Display a listing of the ActionTypes.
     *
     * @param ActionTypesDataTable $actionTypesDataTable
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(ActionTypesDataTable $actionTypesDataTable)
    {
        return $actionTypesDataTable->render('action_types.index');
    }

    /**
     * Show the form for creating a new ActionTypes.
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function create()
    {
        return view('action_types.create');
    }

    /**
     * Store a newly created ActionTypes in storage.
     *
     * @param CreateActionTypesRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function store(CreateActionTypesRequest $request)
    {
        $input = $request->all();

        $actionTypes = $this->actionTypesRepository->create($input);

        Flash::success('Tipo de actuación creada correctamente');

        return redirect(route('actionTypes.index'));
    }

    /**
     * Display the specified ActionTypes.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function show($id)
    {
        $actionTypes = $this->actionTypesRepository->find($id);

        if (empty($actionTypes)) {
            Flash::error('Tipo de actuación no encontrado');

            return redirect(route('actionTypes.index'));
        }

        return view('action_types.show')->with('actionTypes', $actionTypes);
    }

    /**
     * Show the form for editing the specified ActionTypes.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function edit($id)
    {
        $actionTypes = $this->actionTypesRepository->find($id);

        if (empty($actionTypes)) {
            Flash::error('Tipo de actuación no encontrado');

            return redirect(route('actionTypes.index'));
        }

        return view('action_types.edit')->with('actionTypes', $actionTypes);
    }

    /**
     * Update the specified ActionTypes in storage.
     *
     * @param  int              $id
     * @param UpdateActionTypesRequest $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function update($id, UpdateActionTypesRequest $request)
    {
        $actionTypes = $this->actionTypesRepository->find($id);

        if (empty($actionTypes)) {
            Flash::error('Tipo de actuación no encontrado');

            return redirect(route('actionTypes.index'));
        }

        $actionTypes = $this->actionTypesRepository->update($request->all(), $id);

        Flash::success('Tipo de actuación actualizada correctamente');

        return redirect(route('actionTypes.index'));
    }

    /**
     * Remove the specified ActionTypes from storage.
     *
     * @param  int $id
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function destroy($id)
    {
        $actionTypes = $this->actionTypesRepository->find($id);

        if (empty($actionTypes)) {
            Flash::error('Tipo de actuación no encontrado');

            return redirect(route('actionTypes.index'));
        }

        $this->actionTypesRepository->delete($id);

        Flash::success('Tipo de actuación eliminada correctamente.');

        return redirect(route('actionTypes.index'));
    }
}

resources/views/action_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo de actuación
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'actionTypes.store']) !!}

                        @include('action_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/action_types/datatables_actions.blade.php
{!! Form::open(['route' => ['actionTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <!-- <a href="{{ route('actionTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a> -->
    <a href="{{ route('actionTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/action_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Action Types
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($actionTypes, ['route' => ['actionTypes.update', $actionTypes->id], 'method' => 'patch']) !!}

                        @include('action_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/action_types/fields.blade.php
<!-- Action Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Tipo de actuacion', 'Tipo de actuacion:') !!}
    {!! Form::text('action_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('actionTypes.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/action_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tipos de actuaciones</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('actionTypes.create') }}">Agregar nuevo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('action_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/action_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Action Types
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('action_types.show_fields')
                    <a href="{{ route('actionTypes.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/action_types/show_fields.blade.php
<!-- Action Type Field -->
<div class="form-group">
    {!! Form::label('action_type', 'Action Type:') !!}
    <p>{{ $actionTypes->action_type }}</p>
</div>

resources/views/action_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection
<div class="table-responsive">
	{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered table-responsive']) !!}
</div>
@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection